# Generated by Django 2.0.2 on 2018-03-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20180321_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedNotificationRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(blank=True, db_index=True, max_length=360, null=True)),
                ('task_ref', models.CharField(blank=True, db_index=True, max_length=360, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delayed_notification_refs', to='accounts.Account')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'error')], null=True)),
                ('verb', models.IntegerField(choices=[(1, 'account welcome'), (2, 'account approved'), (3, 'password reset'), (4, 'received message'), (5, 'classified expired'), (6, 'classified posted'), (7, 'added to organization'), (8, 'accepted adding to organization'), (9, 'account invite')], db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, db_index=True, max_length=360, null=True)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=360, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='UserEmailNotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_verb', models.IntegerField(blank=True, choices=[(1, 'account welcome'), (2, 'account approved'), (3, 'password reset'), (4, 'received message'), (5, 'classified expired'), (6, 'classified posted'), (7, 'added to organization'), (8, 'accepted adding to organization'), (9, 'account invite')], db_index=True, null=True)),
                ('enable', models.NullBooleanField()),
                ('token', models.CharField(blank=True, db_index=True, max_length=360, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sauser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_settings', to='accounts.SAUser')),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
