# Generated by Django 2.0.2 on 2018-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'notification verb')], db_index=True),
        ),
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='notification_verb',
            field=models.IntegerField(blank=True, choices=[(1, 'notification verb')], db_index=True, null=True),
        ),
    ]
