# Generated by Django 2.0.2 on 2018-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180321_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'welcome'), (2, 'password reset')], db_index=True),
        ),
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='notification_verb',
            field=models.IntegerField(blank=True, choices=[(1, 'welcome'), (2, 'password reset')], db_index=True, null=True),
        ),
    ]
