# Generated by Django 2.0.2 on 2018-04-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180407_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'welcome'), (2, 'password reset'), (3, 'new offer')], db_index=True),
        ),
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='notification_verb',
            field=models.IntegerField(blank=True, choices=[(1, 'welcome'), (2, 'password reset'), (3, 'new offer')], db_index=True, null=True),
        ),
    ]
