# Generated by Django 2.0.2 on 2018-05-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20180412_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.IntegerField(choices=[(1, 'welcome'), (2, 'password reset'), (3, 'new offer'), (4, 'offer resolve')], db_index=True),
        ),
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='notification_verb',
            field=models.IntegerField(blank=True, choices=[(1, 'welcome'), (2, 'password reset'), (3, 'new offer'), (4, 'offer resolve')], db_index=True, null=True),
        ),
    ]
