# Generated by Django 2.0.2 on 2018-05-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180506_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useremailnotificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
