# Generated by Django 2.0.2 on 2018-04-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180407_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
