# Generated by Django 2.0.2 on 2018-05-16 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APITracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('path', models.CharField(blank=True, max_length=1000, null=True)),
                ('hijack', models.BooleanField(default=False)),
                ('request_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time_spent', models.FloatField(blank=True, default=0, null=True)),
                ('status_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
