# Generated by Django 2.0.2 on 2018-05-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usertracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitracking',
            name='hijack',
        ),
    ]
