# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name=b'Sender')),
                ('recipient', models.TextField(verbose_name=b'Recipient')),
                ('content', models.TextField(verbose_name=b'Email Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('excepion_type_and_value', models.TextField(verbose_name=b'Excepion Type and Value')),
                ('exception_traceback', models.TextField(verbose_name=b'TraceBack')),
            ],
        ),
    ]
