# Generated by Django 2.0.2 on 2018-03-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='FailedEmails',
        ),
    ]
