# Generated by Django 2.0.2 on 2018-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_item_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='activated',
            new_name='active',
        ),
    ]
