# Generated by Django 2.0.2 on 2018-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20180407_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_good_faith_money',
            field=models.BooleanField(default=False),
        ),
    ]
