# Generated by Django 2.0.2 on 2018-04-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0007_auto_20180408_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='charge_token',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
