# Generated by Django 2.0.2 on 2018-04-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_offer_charge_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
