# Generated by Django 2.0.2 on 2018-04-11 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_activation_token'),
        ('markets', '0009_auto_20180409_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_subscription', to='markets.Item')),
                ('sa_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_subscription', to='accounts.SAUser')),
            ],
        ),
    ]
