# Generated by Django 2.0.2 on 2018-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_waitinglistsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistsubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
