# Generated by Django 2.0.2 on 2018-06-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
