# Generated by Django 2.0.2 on 2018-10-27 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180519_0217'),
        ('markets', '0016_offer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(1, 'owner'), (2, 'buyer'), (3, 'seller'), (4, 'requested')], db_index=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplacememberships', to='markets.Marketplace')),
                ('sa_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplacememberships', to='accounts.SAUser')),
            ],
        ),
    ]
