# Generated by Django 2.0.2 on 2018-10-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_marketplace_marketplacemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='markets.Marketplace'),
        ),
    ]
