# Generated by Django 2.0.2 on 2018-10-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0019_auto_20181027_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='name',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
